### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by jradavenport** [ethankruse/koi3278#1]
As has been pointed out to me recently, you should really include a LICENSE file so that people can include your code in their analysis. You might want to choose a slightly more restricted license for this, or maybe not. I found @jakevdp 's writeup on astrobetter useful for this:
http://www.astrobetter.com/the-whys-and-hows-of-licensing-scientific-code/

**Comment by ethankruse** [comment]
Only 17 months later, and I listened to you!

**Comment by jakevdp** [comment]
Like
